### ISSUE TITLE
Fix wifi support

### ISSUE THREAD

**Issue by edisonf** [uvdl/yocto-ornl#1]
Wifi support is disabled in current build

**Comment by edisonf** [comment]
Take a look at branch https://github.com/uvdl/yocto-ornl/tree/feature/yocto_sumo

Wifi support is already working

**Comment by bvacaliuc** [comment]
I think there is something missing still.  The interface is up but the driver rejects some ops:
```
root@var-som-mx6-ornl:~# cat /etc/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
  ssid="XXX"
  scan_ssid=1
  key_mgmt=WPA-PSK
  psk="XXX"
}
root@var-som-mx6-ornl:~# ifdown -v wlan0
run-parts /etc/network/if-down.d
true
ip addr flush dev wlan0 label wlan0
ip link set wlan0 down
wlcore: down
run-parts /etc/network/if-post-down.d

root@var-som-mx6-ornl:~# ifup -v wlan0
run-parts /etc/network/if-pre-up.d
Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
ioctl[SIOCSIWMODE]: Operation not supported
ioctl[SIOCGIWRANGE]: Operation not supported
ioctl[SIOCGIWMODE]: Operation not supported
ioctl[SIOCSIWAP]: Operation not supported
ioctl[SIOCSIWESSID]: Operation not supported
ioctl[SIOCSIWENCODEEXT]: Operation not supported
ioctl[SIOCSIWENCODE]: Operation not supported
ioctl[SIOCSIWENCODEEXT]: Operation not supported
ioctl[SIOCSIWENCODE]: Operation not supported
ioctl[SIOCSIWENCODEEXT]: Operation not supported
ioctl[SIOCSIWENCODE]: Operation not supported
ioctl[SIOCSIWENCODEEXT]: Operation not supported
ioctl[SIOCSIWENCODE]: Operation not supported
ip link set wlan0 up
true
run-parts /etc/network/if-up.d

root@var-som-mx6-ornl:~# ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr f0:45:da:f1:48:e7
          UP BROADCAST MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by edisonf** [comment]
You can follow these 2 wikis:

http://variwiki.com/index.php?title=VAR-SOM-MX6_Wireless_LAN
https://wiki.archlinux.org/index.php/ConnMan#Connecting_to_a_protected_access_point

Here is what I did:

<pre>
root@var-som-mx6-ornl:/usr/bin/wlconf# ./configure-device.sh 

Please provide the following information.

Are you using a TI module? [y/n] : y
What is the chip flavor? [1801/1805/1807/1831/1835/1837 or 0 for unknown] : 0
How many 2.4GHz antennas are fitted? [1/2] : 1
How many 5GHz antennas are fitted (using 2 antennas requires a proper switch)? [0/1/2] : 0
Should SISO40 support be applied? [y/n] : y
wlcore: down
wlan0: deauthenticating from 60:38:e0:98:48:ba by local choice (Reason: 3=DEAUTH_LEAVING)
wlcore: down
IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
IPv6: ADDRCONF(NETDEV_UP): sit0: link is not ready

The device has been successfully configured.
TI Module: y
Chip Flavor: 0
Number of 2.4GHz Antennas Fitted: 1
Number of 5GHz Antennas Fitted: 0
Diversity Support: n
SISO40 Support: y
Japanese Standards Applied: n
Class 2 Permissive Change (C2PC) Applied: n

wlcore: wl18xx HW: 183x or 180x, PG 2.2 (ROM 0x11)
wlcore: loaded
root@var-som-mx6-ornl:/usr/bin/wlconf# wlcore: PHY firmware version: Rev 8.2.0.0.242
wlcore: firmware booted (Rev 8.9.0.0.79)
IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
wlan0: authenticate with 60:38:e0:98:48:ba
wlan0: send auth to 60:38:e0:98:48:ba (try 1/3)
wlan0: authenticated
wlan0: associate with 60:38:e0:98:48:ba (try 1/3)
wlan0: RX AssocResp from 60:38:e0:98:48:ba (capab=0x411 status=0 aid=21)
wlan0: associated
IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
wlcore: Association completed.

root@var-som-mx6-ornl:/usr/bin/wlconf# 
root@var-som-mx6-ornl:/usr/bin/wlconf# 
root@var-som-mx6-ornl:/usr/bin/wlconf# 
root@var-som-mx6-ornl:/usr/bin/wlconf# connmanctl 
connmanctl> scan wifi
Scan completed for wifi
connmanctl> services
    REL                  wifi_a81b6a8fc0f0_52454c_managed_psk
connmanctl> agent on
Agent registered
connmanctl> connect wifi_a81b6a8fc0f0_52454c_managed_psk
connmanctl> wlan0: authenticate with 60:38:e0:98:48:ba
wlan0: send auth to 60:38:e0:98:48:ba (try 1/3)
Error /net/connman/service/wifi_wlan0: aborting authentication with 60:38:e0:98:48:ba by local choice (Reason: 3=DEAUTH_LEAVING)
a81b6a8fc0f0_52454c_managed_psk: Operation aborted
connmanctl> wlan0: authenticate with 60:38:e0:98:48:ba
wlan0: send auth to 60:38:e0:98:48:ba (try 1/3)
wlan0: authenticated
wlan0: associate with 60:38:e0:98:48:ba (try 1/3)
wlan0: RX AssocResp from 60:38:e0:98:48:ba (capab=0x411 status=0 aid=21)
wlan0: associated
IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
wlcore: Association completed.

connmanctl> quit
root@var-som-mx6-ornl:/usr/bin/wlconf# ifconfig
eth0      Link encap:Ethernet  HWaddr f8:dc:7a:0d:a9:37  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:3591 errors:0 dropped:0 overruns:0 frame:0
          TX packets:96 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:390241 (381.0 KiB)  TX bytes:11844 (11.5 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:2188 (2.1 KiB)  TX bytes:2188 (2.1 KiB)

wlan0     Link encap:Ethernet  HWaddr a8:1b:6a:8f:c0:f0  
          inet addr:192.168.1.36  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::aa1b:6aff:fe8f:c0f0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:141 errors:0 dropped:0 overruns:0 frame:0
          TX packets:151 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:17152 (16.7 KiB)  TX bytes:28110 (27.4 KiB)

root@var-som-mx6-ornl:/usr/bin/wlconf# ping www.google.com
PING www.google.com (74.125.141.103) 56(84) bytes of data.
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=1 ttl=45 time=55.3 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=2 ttl=45 time=69.1 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=3 ttl=45 time=94.8 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=4 ttl=45 time=68.9 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=5 ttl=45 time=69.1 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=6 ttl=45 time=69.7 ms
64 bytes from vl-in-f103.1e100.net (74.125.141.103): icmp_seq=7 ttl=45 time=69.7 ms
</pre>

**Comment by bvacaliuc** [comment]
Ok, that worked.  Thanks for the info.

**Comment by bvacaliuc** [comment]
FYI, as of this commit: https://github.com/uvdl/yocto-ornl/commit/a8556a1780f6f8edf1bec8e520f7051680b6338a wifi support on Iris 2.0 R0 is inoperative again.

**Comment by edisonf** [comment]
It is still working for me in DT6C, maybe is something in Iris2, I can try to reproduce it when I have the HW.

**Comment by bvacaliuc** [comment]
It cannot be an Iris 2 issue, because on the DART-MX6, the WiFi chip is on board the cpu module.  If it works in DT6C then it must work in Iris 2 unless the device tree has interfered somehow.  However, it was shown to work with some version of Iris 2, so the only possibility is the difference between working and not working.  i.e. from https://github.com/uvdl/yocto-ornl/commit/1ad3694ca343047293be5f954a41274645eaa750 to https://github.com/uvdl/yocto-ornl/commit/a8556a1780f6f8edf1bec8e520f7051680b6338a

**Comment by edisonf** [comment]
Yes, I meant something in the device tree for Iris2, not the HW. I'll see if I can find what could have changed that caused the issue.

**Comment by bvacaliuc** [comment]
still a problem with https://github.com/uvdl/linux-imx/commit/4e7c086a33f29cd9a006be20eae5c07ef04a7cb6

**Comment by bvacaliuc** [comment]
nevermind, Network Manager support was added here: https://github.com/uvdl/yocto-ornl/issues/11 and that is working after starting NetworkManager after boot.
