### ISSUE TITLE
add V4L2 support

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#12]
```
root@var-som-mx6-ornl:~# ls /dev/video*
/dev/video0  /dev/video16  /dev/video17
root@var-som-mx6-ornl:~# v4l2-ctl -d /dev/video0 --list-formats
-sh: v4l2-ctl: command not found
```

Video For Linux has been excellent in getting access to a variety of USB cameras and is needed for the various gstreamer piplelines we are developing.

**Comment by edisonf** [comment]
Understood, I'll enable v4l-utils in the yocto build

**Comment by edisonf** [comment]
I just added v4l-utils to the yocto layer [here](https://github.com/uvdl/yocto-ornl/commit/b9dd1a1ac4331eb22d1c5425d3613ae56c5019e1).
