### ISSUE TITLE
add systemd support

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#13]
```
root@var-som-mx6-ornl:~# systemctl status
-sh: systemctl: command not found
```

We have many systemd service scripts that we use for a variety of tasks.  We would require this to be part of our yocto image build.

**Comment by edisonf** [comment]
I just enabled systemd support in [this branch](https://github.com/uvdl/yocto-ornl/tree/feature/systemd).

In order to test it just make sure your "build/conf/local.conf" has [these lines](https://github.com/uvdl/yocto-ornl/commit/be850713732f172e0e604c8959780d6afe3eabb3)

**Comment by waddle77** [comment]
Way old.  This has been in for years now.
