### ISSUE TITLE
add RTMP gstreamer sink

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#14]
In the [debian-var] build, we have the following gstreamer capabilities:
[debian-var-gst-inspect-1.0.txt](https://github.com/uvdl/yocto-ornl/files/3187697/debian-var-gst-inspect-1.0.txt)

In the [yocto-ornl] distribution, we have these:
[yocto-ornl-gst-inspect-1.0.txt](https://github.com/uvdl/yocto-ornl/files/3187698/yocto-ornl-gst-inspect-1.0.txt)

We need at least the 'rtmpsink' added from the 'rtmp' group.

**Comment by edisonf** [comment]
I just added the plugin [here](https://github.com/uvdl/yocto-ornl/commit/0874758fb3ad676314e1c4ec5f16d1c5d435146a)

**Comment by waddle77** [comment]
Old, more than likely resolved? Closing it.
