### ISSUE TITLE
merge kernel work

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#15]
Features added on https://github.com/uvdl/linux-imx need to be added to the https://github.com/uvdl/yocto-ornl/tree/develop branch.

 - [ ] [linux-imx@project/ksz9897-microchip-no-fec-mod](https://github.com/uvdl/linux-imx/tree/project/ksz9897-microchip-no-fec-mod)
 - [ ] [linux-imx@feature/tc358743-support](https://github.com/uvdl/linux-imx/tree/feature/tc358743-support)
 - [ ] [linux-imx@imx_4.9.88_2.0.0_ga-iris2-R1](https://github.com/uvdl/linux-imx/tree/imx_4.9.88_2.0.0_ga-iris2-R1)

These are being merged in [linux-imx@feature/iris2](https://github.com/uvdl/linux-imx/tree/feature/iris2), and we want to roll-up these edits into a master build that has the core features and settings needed.

**Comment by bvacaliuc** [comment]
~~The yocto support is in a **state of disorder**.  I recently attempted a branch, https://github.com/uvdl/yocto-ornl/tree/debug/spi-ksz9893, which should have contained several enhancements including the bootloader and the .dtb selection *(at least according to the https://github.com/uvdl/yocto-ornl/network)*.~~

~~The resulting bootsector contains:~~
```
root@IMX6ee6747e01b0459d4:~# ls /media/mmcblk1p1
imx6dl-var-som-cap.dtb       imx6dl-var-som-vsc.dtb  imx6q-var-som-cap.dtb
imx6dl-var-som-res.dtb       imx6qp-var-som-cap.dtb  imx6q-var-som-res.dtb
imx6dl-var-som-solo-cap.dtb  imx6qp-var-som-res.dtb  imx6q-var-som-vsc.dtb
imx6dl-var-som-solo-res.dtb  imx6qp-var-som-vsc.dtb  uImage
imx6dl-var-som-solo-vsc.dtb  imx6q-var-dart.dtb
```

~~Which is indicative not of a modern Iris 2 support kernel, but of an older version which overused the 'imx6q-var-dart.dtb' for Iris 2 work and has been deprecated for at least 6 months.~~

**Comment by bvacaliuc** [comment]
Excuse me.  I realized that I had created and downloaded the image but forgot to execute the step to bcopy it to the SD card, so I was booting with an old image.  Sorry about the noise.

**Comment by waddle77** [comment]
Old and crappy.  No longer used / needed. Closing.
