### ISSUE TITLE
merge feature branches

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#16]
Recent experience due to #15 highlight the need to integrate the various feature branches into a working base board support branch.

- [ ] determine why https://github.com/uvdl/yocto-ornl/tree/feature/board_selection appears to have been regressed-out of the develop line
- [ ] https://github.com/uvdl/yocto-ornl/tree/feature/systemd
- [ ] https://github.com/uvdl/yocto-ornl/tree/feature/tc358743-support
- [ ] https://github.com/uvdl/yocto-ornl/tree/feature/uvc-composite-driver

**Comment by waddle77** [comment]
Old and obsolete. Closing.
