### ISSUE TITLE
Fix NAND flash burning support

### ISSUE THREAD

**Issue by edisonf** [uvdl/yocto-ornl#2]
The base Yocto image is pretty rough.  No wifi device, appears to be missing a package manager, and appears to be missing the parts discussing [Yocto NAND Flash Burning](http://variwiki.com/index.php?title=Yocto_NAND_Flash_Burning&release=RELEASE_SUMO_V1.1_VAR-SOM-MX6).

**Comment by waddle77** [comment]
All this is fixed but doesn't matter as we no longer support this system.
