### ISSUE TITLE
python3-python-dateutil build

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#44]
[python3-python-dateutil](https://github.com/uvdl/yocto-ornl/blob/develop/sources/meta-ornl/recipes-python/python3-dateutil/python3-python-dateutil_2.8.1.bb) fails to build.

See:
[do_configure.9386.log](https://github.com/uvdl/yocto-ornl/files/5666585/do_configure.9386.log)

**Comment by bvacaliuc** [comment]
### Notes and Observations about time and date
  * https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
  * https://assert.cc/posts/dateutil-preferred/
  * https://python.libhunt.com/categories/132-date-and-time

**Comment by waddle77** [comment]
Closed. Working now.
