### ISSUE TITLE
would like to automate building the artifacts we really want

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#48]
With d76d788837ad0991cbf2cd7b2e6c8ec0e9abda32, we now have the ability to build everything for the full image to be written on microSD as well as its software update image.

This can be accomplished by:
```
make dependencies
make environment
make toaster
make build
make YOCTO_CMD=var-dev-image-swu build
make archive
# manually copy $YOCTO_DIR/$YOCTO_ENV/tmp/deploy/images/$MACHINE/var-dev-image-swu-$MACHINE.swu to the archive folder for use as a full system update
```

On systems that are already deployed, loading the software update image needs to have a variant that preserves (at least) the IP address of the target that we are updating, because the default is probably not the one the target system is using.

This leads to either:
  a. the device has to be accessed on a different network address and then configured back via the application .swu
  b. we do extra work to manually edit `$YOCTO_DIR/sources/meta-ornl/recipes-core/default-eth0/files/eth0.network` to set the needed IP address before building to ensure that after the update the target comes up on the same IP it did before.

We already do `b)` above for the application `.swu` files that we produce.  I suppose this enhancement request has several parts:

- [ ] Modify the `.swu` image that is produced to *preserve* the installed `/etc/systemd/network/eth0.network` so that the target system comes back up at the same IP address that it currently uses.
- [ ] Add the ability to override the default IP address in `$YOCTO_DIR/sources/meta-ornl/recipes-core/default-eth0/files/eth0.network` from a Makefile variable so that full microSD image can also have a specified (non-default) IP address when built.
- [ ] Update the Makefile so that the `all` target does all the above so that both the microSD image *and* the `.swu` image are produced and collected in one place.  _(usually the build machine is a cloud server and the files need to be moved to where they can be used to make a microSD or be uploaded to a target)_

**Comment by waddle77** [comment]
Obsolete.  These should be handled on a higher level.  As this is a base image the ONLY thing we should focus on is getting a system running with minimal applications.
