### ISSUE TITLE
make environment can fail

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#50]
When attempting to build into a previously setup `$YOCTO_DIR`, you might get an error checking out the `meta-variscite-fslc` repo.  The issue is that we are copying in a script to fix problems in making the sdcard:
```
~/ornl-dart-yocto/sources/meta-variscite-fslc$ git status
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh
```
A workaround is to revert the local changes before calling `repo` on the folder.  A better fix might be to fork `meta-variscite-fslc` and apply the patch that way instead of overriding the script.  Either way, if we do the copy-in, then we need to fix the repo call to match it.

**Comment by waddle77** [comment]
Obsolete.  Closing.
