### ISSUE TITLE
swupdate requires build-time control over listening port

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#58]
During system integration, other applications use port 8080 for web server operations.  Those applications are less easily adjusted so the need is to be able to configure the port used for the swupdate webserver (if it is used) at image build time.

**Comment by bvacaliuc** [comment]
The current swupdate configuration files do not work to change the port.

**Comment by waddle77** [comment]
Closing... This has been fixed since commit f49008be70993182bc63dd0896de480b10dbedab
