### ISSUE TITLE
on board serial ports doesn't work properly in dunfell

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#65]
It was was discovered by the team that the iridium modem would not work and the apparent workaround was made in 324cf7e39f4aa9b99b64a27f5c48c946523147bd of the file [uvdl_kernel_5-4.patch](sources/meta-ornl/recipes-kernel/linux/linux-variscite/var-som-mx6-ornl/uvdl_kernel_5-4.patch).

However, during testing, neither did the `/dev/ttymxc3` work for contact with the flight controller...

So this issue is to track the on-board serial ports.

**Comment by waddle77** [comment]
@bvacaliuc @JKirk865 I thought all the serial ports had been patched.  Recommend closing this issue if thats true.
