### ISSUE TITLE
Update uboot to select iris dtb

### ISSUE THREAD

**Issue by edisonf** [uvdl/yocto-ornl#7]

**Comment by bvacaliuc** [comment]
To identify an Iris 2.0 vs. a DART [DT6CustomBoard](https://www.variscite.com/wp-content/uploads/2017/11/VAR-DT6CustomBoard-Datasheet.pdf), perform the following:
 1. set GPIO4[21] to 100K pull-down
 1. read back pin value:
    a. if LOW, then it is a DT6CustomBoard
    b. if HIGH, then it is an IRIS 2.0 Board

To identify the version of an Iris 2.0, perform the following:
 1. set GPIO4[29] and GPIO4[30] to 100K pull up
 1. read back pin values:

| GPIO4[30] | GPIO4[29] | Revision |
| :---------: | :-----------: | --------: |
| HIGH | HIGH | R0 |
| HIGH | LOW | R1 |
| LOW | HIGH | R2 |
| LOW | LOW | R3 |

**Comment by bvacaliuc** [comment]
Please use `imx6q-iris2-R0.dtb`, `imx6q-iris2-R1.dtb`, etc.

**Comment by edisonf** [comment]
[This branch](https://github.com/uvdl/yocto-ornl/tree/feature/board_selection) should have the support. 

@bvacaliuc , could you please give it a try?

**Comment by bvacaliuc** [comment]
[yocto-feature-board_selection-on-iris2-R0.txt](https://github.com/uvdl/yocto-ornl/files/2818039/yocto-feature-board_selection-on-iris2-R0.txt)

Looks like it still picked the DART configuration...

**Comment by edisonf** [comment]
As I don't have Iris2 HW and GPIO4_21 is not exposed in DT6 I used GPIO1_1 (available at pin 6 of J17) to simulate the board selection. If the pin is not connected, the board boots using dart dtb, if I connect the pin to Vcc, the board boots using imx6q-iris2-R0.dtb. 

Could you please verify if your u-boot has the latest changes? To do so you can just stop at uboot and print findfdt:

<pre>
printenv findfdt
</pre>


You should get something like this:

<pre>
findfdt=if test $fdt_file = undefined; then if test $board_name = IRIS2_R0; then setenv fdt_file imx6q-iris2-R0.dtb; fi; if test $board_name = IRIS2_R1; then setenv fdt_file imx6q-iris2-R1.dtb; fi; if test $board_name = IRIS2_R2; then setenv fdt_file imx6q-iris2-R2.dtb; fi; if test $board_name = IRIS2_R3; then setenv fdt_file imx6q-iris2-R3.dtb; fi; if test $board_name = DT6CUSTOM && test $board_rev = MX6Q; then setenv fdt_file imx6q-var-dart.dtb; fi; if test $board_name = SOLOCUSTOM && test $board_rev = MX6QP; then setenv fdt_file imx6qp-var-som-vsc.dtb; fi; if test $board_name = SOLOCUSTOM && test $board_rev = MX6Q; then setenv fdt_file imx6q-var-som-vsc.dtb; fi; if test $board_name = SOLOCUSTOM && test $board_rev = MX6DL && test $board_som = SOM-SOLO; then setenv fdt_file imx6dl-var-som-solo-vsc.dtb; fi; if test $board_name = SOLOCUSTOM && test $board_rev = MX6DL && test $board_som = SOM-MX6; then setenv fdt_file imx6dl-var-som-vsc.dtb; fi; if test $board_name = MX6CUSTOM && test $board_rev = MX6QP; then i2c dev 2; if i2c probe 0x38; then setenv fdt_file imx6qp-var-som-cap.dtb; else setenv fdt_file imx6qp-var-som-res.dtb; fi; fi; if test $board_name = MX6CUSTOM && test $board_rev = MX6Q; then i2c dev 2; if i2c probe 0x38; then setenv fdt_file imx6q-var-som-cap.dtb; else setenv fdt_file imx6q-var-som-res.dtb; fi; fi; if test $board_name = MX6CUSTOM && test $board_rev = MX6DL && test $board_som = SOM-SOLO; then i2c dev 2; if i2c probe 0x38; then setenv fdt_file imx6dl-var-som-solo-cap.dtb; else setenv fdt_file imx6dl-var-som-solo-res.dtb; fi; fi; if test $board_name = MX6CUSTOM && test $board_rev = MX6DL && test $board_som = SOM-MX6; then i2c dev 2; if i2c probe 0x38; then setenv fdt_file imx6dl-var-som-cap.dtb; else setenv fdt_file imx6dl-var-som-res.dtb; fi; fi; if test $fdt_file = undefined; then echo WARNING: Could not determine dtb to use; fi; fi;
</pre>

Please note the IRIS2_Rx board names at the beginning. 

Also make sure the fdt_file variable is undefined:

<pre>
printenv fdt_file 
fdt_file=undefined
</pre>

**Comment by bvacaliuc** [comment]
Ok, so a few things.

  1. On cold boot (using https://github.com/uvdl/yocto-ornl/commit/a8556a1780f6f8edf1bec8e520f7051680b6338a), this seems to work:
```
...
Hit any key to stop autoboot:  0
=> printenv fdt_file
fdt_file=undefined
=> printenv board_name
board_name=IRIS2_R0
=> boot
switch to partitions #0, OK
mmc0 is current device
reading /uEnv.txt
** Unable to read file /uEnv.txt **
reading /boot.scr
** Unable to read file /boot.scr **
reading /uImage
7105192 bytes read in 355 ms (19.1 MiB/s)
Booting from mmc ...
fdt_file=imx6q-iris2-R0.dtb
reading /imx6q-iris2-R0.dtb
47267 bytes read in 24 ms (1.9 MiB/s)
## Booting kernel from Legacy Image at 12000000 ...
```

  2. However, if a halt/power off/power on sequence is performed, there is an issue:
```
...
reboot: Power down
▒
U-Boot SPL 2017.03-mx6+ga7869c2 (Feb 08 2019 - 20:10:30)

Part number: VSM-DT6-302A
Assembly: AS1811142105
Date of production: 2018Dec05
Trying to boot from MMC1
MMC Boot Device: mmc0 (SD)


U-Boot 2017.03-mx6+ga7869c2 (Feb 08 2019 - 20:10:30 +0000)

CPU:   Freescale i.MX6Q rev1.6 at 792MHz
CPU:   Extended Commercial temperature grade (-20C to 105C) at 42C
Reset cause: POR
Board: Variscite DART-MX6
I2C:   ready
DRAM:  1 GiB
PMIC:  PFUZE100 ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
*** Warning - bad CRC, using default environment

auto-detected panel VAR-WVGA
Display: VAR-WVGA (800x480)
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc0 is current device
eMMC:  7.3 GiB
Net:   using phy at 7
got MAC0 address from fuse: f8:dc:7a:22:b0:02
FEC [PRIME]
Normal Boot
Hit any key to stop autoboot:  0
MMC: no card present
mmc_init: -123, time 2
MMC: no card present
mmc_init: -123, time 2
Booting from net ...
FEC Waiting for PHY auto negotiation to complete......... TIMEOUT !
Could not initialize PHY FEC
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3
BOOTP broadcast 4

Abort
fdt_file=imx6q-iris2-R0.dtb
FEC Waiting for PHY auto negotiation to complete....user interrupt!
Could not initialize PHY FEC
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3

Abort
Wrong Image Format for bootm command
ERROR: can't get kernel image!
=>
```

The detection of the SD card present seems to be intermittent.  I'm not sure that the yocto u-boot is 100% reliable.  I think we should use the u-boot from the debian image builder.  For example:
`U-Boot SPL 2017.03-27254-g466898d` (reliable), `U-Boot SPL 2017.03-mx6+ga7869c2` (not reliable)

**Comment by edisonf** [comment]
It works for me on DT6C but we are using different DTB files, I'll try to reproduce the issue when we have the HW.

**Comment by bvacaliuc** [comment]
I have verified that this is working on Iris2 R0 and DT6C hardware with https://github.com/uvdl/uboot-imx on the iris2 branch.
