### ISSUE TITLE
do_roofts fails on some component

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#71]
> ERROR: var-dev-update-full-image-1.0-r0 do_rootfs: Unable to install packages. Command '/ephemeral/yocto-ornl-dunfell/build_ornl/tmp/work/var_som_mx6_ornl-fslc-linux-gnueabi/var-dev-update-full-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /ephemeral/yocto-ornl-dunfell/build_ornl/tmp/work/var_som_mx6_ornl-fslc-linux-gnueabi/var-dev-update-full-image/1.0-r0/opkg.conf -t /ephemeral/yocto-ornl-dunfell/build_ornl/tmp/work/var_som_mx6_ornl-fslc-linux-gnueabi/var-dev-update-full-image/1.0-r0/temp/ipktemp/ -o /ephemeral/yocto-ornl-dunfell/build_ornl/tmp/work/var_som_mx6_ornl-fslc-linux-gnueabi/var-dev-update-full-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install base-passwd bind-utils default-eth0 dotnet-core dtc elp-h264 flex fsl-rc-local gcc git gps-utils gpsd gst-interpipe gstd gstreamer1.0-plugins-ugly htop i2c-tools imx-test iotop iperf3 kernel-devicetree kernel-image ksz-initscripts libgps libsodium libsodium-dev libtool libxml2-dev libxslt-dev m4 make mfgtest minicom nano net-tools networkmanager nload nodejs ntp ntp-bin openssl openssl-bin packagegroup-base-extended packagegroup-cockpit packagegroup-core-boot packagegroup-core-full-cmdline packagegroup-core-sdk packagegroup-core-ssh-openssh packagegroup-core-standalone-sdk-target packagegroup-core-tools-debug packagegroup-fsl-gstreamer1.0 packagegroup-fsl-gstreamer1.0-full packagegroup-fsl-tools-benchmark packagegroup-fsl-tools-gpu packagegroup-fsl-tools-gpu-external packagegroup-fsl-tools-testapps packagegroup-imx-tools-audio packagegroup-tools-bluetooth perf pkgconfig postinstall powertop psplash python3 python3-bottle python3-dev python3-future python3-lxml python3-mavproxy python3-netifaces python3-numpy python3-pexpect python3-pip python3-protobuf python3-pymavlink python3-pynmea2 python3-pyserial python3-pytz python3-pyyaml python3-requests python3-uptime python3-urllib3 run-postinsts screen shadow strace sudo swupdate swupdate-www systemd-analyze tcpdump u-boot-variscite v4l-utils vsdbg webcam-tools x264 x265' returned 255:

This causes a `var-dev-update-full-image` build to fail, although most items are successfully installed.  Current workaround is to ignore the exit code in the Makefile to continue with the build steps, but this is a bad hack.

**Comment by bvacaliuc** [comment]
This has been happening since we stopped building `thud` and started building `dunfell`.

**Comment by bvacaliuc** [comment]
[log.do_rootfs.txt](https://github.com/uvdl/yocto-ornl/files/6787188/log.do_rootfs.txt)

That's the log file with the error.

**Comment by bvacaliuc** [comment]
This is now catastrophic after an attempt to merge with #69 , no root file system is produced and no SD card image is produced either.

**Comment by waddle77** [comment]
What are you using? My branch builds with make environment and make build. I added in some Dev tools but the dotnet and earlier builds with no issues for me. I'll do another build later.

**Comment by bvacaliuc** [comment]
Using #67 , your last patch helped.  Looking much better.  Both rootfs and swu can build now.  There is a residual QA issue which comes out as an ERROR and still requires us to ignore the exit code of the full image build:

```
WARNING: linux-variscite-5.4.85+gitAUTOINC+343970224e-r0 do_kernel_metadata: [NOTE]: defconfig was supplied both via KBUILD_DEFCONFIG and SRC_URI. Dropping SRC_URI defconfig
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-src went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-dbg went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-archive went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-tests went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-perl went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-python went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-staticdev went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-dev went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-doc went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf-locale went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
ERROR: perf-1.0-r9 do_packagedata: QA Issue: Package version for package perf went backwards which would break package feeds (from 0:5.4.85+gef3e928cdd43-r9 to 0:5.4.85+g76c85cd7ee66-r9) [version-going-backwards]
WARNING: var-dev-update-full-image-1.0-r0 do_rootfs: The license listed Microsoft_Software_License was not in the licenses collected for recipe vsdbg
NOTE: Tasks Summary: Attempted 7551 tasks of which 6967 didn't need to be rerun and all succeeded.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 17 seconds

Summary: There were 2 WARNING messages shown.
Summary: There were 11 ERROR messages shown, returning a non-zero exit code.
Makefile:161: recipe for target 'build' failed
make[1]: *** [build] Error 1
Makefile:147: recipe for target 'all' failed
make: [all] Error 2 (ignored)
```
But if we ignore that and move on, the archive is produced and creates an SD card.  *(boot test pending)*

**Comment by waddle77** [comment]
Recommend closing this and linked to PR #67 as this issue was fixed with that.  The other "errors" can be fixed by starting a new build or removing the old perf packages from work and sstate folders.  Its just an error saying that the perf packages went down in version from where we were.

**Comment by waddle77** [comment]
Error seems to be resolved.
