### ISSUE TITLE
raise python3 level to 3.6+ is possible

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#74]
There is a dependency issue when trying to use [pyubx2](https://github.com/semuconsulting/pyubx2) as it depends on Python 3.6+, but the current built python version for Variscite boards is 3.5.6.

If the base OS could be 3.6.? it would be of some benefit.

**Comment by waddle77** [comment]
@bvacaliuc What version are you building? I think dunfell builds with 3.8.

**Comment by waddle77** [comment]
Issue resolved with addition of dunfell.
