### ISSUE TITLE
add pyubx2 to production and development images

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#75]
Would like to have [pyubx2](https://github.com/semuconsulting/pyubx2) added to prod and dev images.

See also #74

**Comment by waddle77** [comment]
See it.  I'll work on this and get a fix up today.

**Comment by waddle77** [comment]
The above PR should fix your issue @bvacaliuc 

Actually, this only fixes it if you are building with dunfell (which has python --version -> 3.8.x)

**Comment by bvacaliuc** [comment]
that should be ok, we want to go that way anyway.

**Comment by waddle77** [comment]
Issue resolved.
