### ISSUE TITLE
Add KSZ driver tools

### ISSUE THREAD

**Issue by edisonf** [uvdl/yocto-ornl#9]
from @bvacaliuc

we are going to need to add [setup_sw.c](https://github.com/Microchip-Ethernet/EVB-KSZ9477/blob/master/KSZ/linux-drivers/ksz9897/linux-4.9/doc/setup_sw.c), [regs_bin](https://github.com/Microchip-Ethernet/EVB-KSZ9477/tree/master/KSZ/linux-drivers/ksz9897/linux-4.9/tools/regs_bin) at the least.

**Comment by waddle77** [comment]
Old.  Hardware no longer supported.
